# Generated by Django 3.2 on 2023-02-02 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onshop', '0003_auto_20230131_0144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rubric',
            options={'ordering': ['name'], 'verbose_name': 'Rubric', 'verbose_name_plural': 'Rubrics'},
        ),
        migrations.AlterField(
            model_name='rubric',
            name='name',
            field=models.CharField(db_index=True, max_length=30, verbose_name='name'),
        ),
    ]
