# Generated by Django 3.2 on 2023-02-02 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onshop', '0005_product_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rubric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='onshop.rubric', verbose_name='Рубрика'),
        ),
    ]
